[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://ext.same-assets.com/3043200819/3269827270.png",
    "https://ext.same-assets.com/3043200819/399659983.png",
    "https://ext.same-assets.com/3043200819/281542554.png",
    "https://ext.same-assets.com/3043200819/2714095024.png",
    "https://ext.same-assets.com/3043200819/2228443562.png",
    "https://ext.same-assets.com/3043200819/3343443258.png",
    "https://ext.same-assets.com/3043200819/1374159968.png",
    "https://ext.same-assets.com/3043200819/1970707969.png",
    "https://ext.same-assets.com/3043200819/849522504.png"
  ]
